"""
Demo Seed Fixtures for Buyer Matching & Demand Aggregation Subsystem.
Explicitly labeled with provenance_status: DEMO, is_demo: True.
Used strictly for demonstration, offline execution, and integration testing.
SIH26132 — Strengthening Market Linkages and Price Discovery for Farmers.
"""

from datetime import date
from typing import Any, Dict, List

# Benchmark Buyer Centroids & Profiles in Chandigarh-Punjab-Haryana-Delhi Corridor
DEMO_BUYERS: List[Dict[str, Any]] = [
    {
        "id": "buyer_wholesaler_ch",
        "display_name": "Chandigarh Fresh Wholesale Hub",
        "buyer_type": "wholesaler",
        "location": "Chandigarh APMC Sector 26",
        "latitude": 30.7333,
        "longitude": 76.7794,
        "active_status": True,
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REG-CH-WHOLESALE-01",
        "source_reference": "Mandi Trader Directory 2024 (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "buyer_processor_delhi",
        "display_name": "Northern Agro Food Processors Ltd",
        "buyer_type": "processor",
        "location": "Sonipat Food Park (near Delhi)",
        "latitude": 28.9931,
        "longitude": 77.0151,
        "active_status": True,
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REG-DL-PROCESS-44",
        "source_reference": "MoFPI Mega Food Park Directory (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "buyer_retail_chain_pkl",
        "display_name": "KiranaFresh Modern Retail Logistics",
        "buyer_type": "retailer",
        "location": "Panchkula Industrial Area Phase II",
        "latitude": 30.6942,
        "longitude": 76.8606,
        "active_status": True,
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REG-HR-RETAIL-12",
        "source_reference": "Corporate Procurement Network (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "buyer_fpo_aggregator_pb",
        "display_name": "Malwa Kisan Samriddhi FPO Aggregator",
        "buyer_type": "aggregator",
        "location": "Patiala Mandi Bypass",
        "latitude": 30.3398,
        "longitude": 76.3869,
        "active_status": True,
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REG-PB-FPO-88",
        "source_reference": "SFAC FPO Registry (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "buyer_exporter_delhi",
        "display_name": "Indo-Gulf Fresh Exports Cargo",
        "buyer_type": "exporter",
        "location": "Azadpur Terminal Mandi / IGI Cargo",
        "latitude": 28.7159,
        "longitude": 77.1772,
        "active_status": True,
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REG-DL-EXP-09",
        "source_reference": "APEDA Exporter Registry (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "buyer_cooperative_haryana",
        "display_name": "Haryana Krishi Sahakari Sangh (HAFED Center)",
        "buyer_type": "cooperative",
        "location": "Kalka Procurement Yard",
        "latitude": 30.8354,
        "longitude": 76.9351,
        "active_status": True,
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REG-HR-COOP-03",
        "source_reference": "State Cooperative Federation (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]

# Procurement Specifications & Commercial Terms
DEMO_BUYER_REQUIREMENTS: List[Dict[str, Any]] = [
    # 1. Wholesaler Chandigarh - Tomato
    {
        "id": "req_wholesaler_ch_tomato",
        "buyer_id": "buyer_wholesaler_ch",
        "commodity_id": "tomato",
        "variety": "Hybrid / Desi",
        "minimum_quantity_kg": 500.0,
        "maximum_quantity_kg": 5000.0,
        "preferred_quality_grade": "GRADE_A",
        "acceptable_quality_range": ["GRADE_A", "GRADE_B"],
        "required_from": date(2024, 9, 15),
        "required_until": date(2024, 9, 25),
        "delivery_mode": "MANDI_GATE",
        "delivery_location": "Chandigarh APMC Gate 2",
        "delivery_latitude": 30.7333,
        "delivery_longitude": 76.7794,
        "price_basis": "FIXED_QUOTE",
        "quoted_price": 29.50,
        "currency": "INR",
        "price_unit": "INR_PER_KG",
        "payment_terms": "IMMEDIATE_CASH",
        "validity_start": date(2024, 9, 15),
        "validity_end": date(2024, 9, 25),
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REQ-CH-TOM-01",
        "source_reference": "Mandi Board Quotation (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # 2. Modern Retail Chain Panchkula - Tomato (Premium Quality)
    {
        "id": "req_retail_pkl_tomato",
        "buyer_id": "buyer_retail_chain_pkl",
        "commodity_id": "tomato",
        "variety": "Firm Red Hybrid",
        "minimum_quantity_kg": 1000.0,
        "maximum_quantity_kg": 8000.0,
        "preferred_quality_grade": "GRADE_A",
        "acceptable_quality_range": ["GRADE_A"],
        "required_from": date(2024, 9, 15),
        "required_until": date(2024, 9, 28),
        "delivery_mode": "BUYER_PREMISES",
        "delivery_location": "KiranaFresh DC Panchkula",
        "delivery_latitude": 30.6942,
        "delivery_longitude": 76.8606,
        "price_basis": "FIXED_QUOTE",
        "quoted_price": 31.00,
        "currency": "INR",
        "price_unit": "INR_PER_KG",
        "payment_terms": "NET_3_DAYS",
        "validity_start": date(2024, 9, 15),
        "validity_end": date(2024, 9, 28),
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REQ-PKL-TOM-02",
        "source_reference": "Retail Supply RFP (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # 3. Processor Delhi / Sonipat - Tomato (Bulk Processing, Accepts Grade B/C)
    {
        "id": "req_processor_delhi_tomato",
        "buyer_id": "buyer_processor_delhi",
        "commodity_id": "tomato",
        "variety": "Processing / Paste Grade",
        "minimum_quantity_kg": 5000.0,
        "maximum_quantity_kg": 40000.0,
        "preferred_quality_grade": "GRADE_B",
        "acceptable_quality_range": ["GRADE_A", "GRADE_B", "GRADE_C"],
        "required_from": date(2024, 9, 16),
        "required_until": date(2024, 10, 5),
        "delivery_mode": "BUYER_PREMISES",
        "delivery_location": "Northern Agro Processing Plant, Sonipat",
        "delivery_latitude": 28.9931,
        "delivery_longitude": 77.0151,
        "price_basis": "FIXED_QUOTE",
        "quoted_price": 27.00,
        "currency": "INR",
        "price_unit": "INR_PER_KG",
        "payment_terms": "NET_7_DAYS",
        "validity_start": date(2024, 9, 16),
        "validity_end": date(2024, 10, 5),
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REQ-DL-TOM-03",
        "source_reference": "Processing Factory Purchase Indent (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # 4. FPO Aggregator Patiala - Onion
    {
        "id": "req_fpo_pb_onion",
        "buyer_id": "buyer_fpo_aggregator_pb",
        "commodity_id": "onion",
        "variety": "Nasik Red / Medium",
        "minimum_quantity_kg": 2000.0,
        "maximum_quantity_kg": 15000.0,
        "preferred_quality_grade": "GRADE_B",
        "acceptable_quality_range": ["GRADE_A", "GRADE_B"],
        "required_from": date(2024, 9, 15),
        "required_until": date(2024, 9, 30),
        "delivery_mode": "EX_FARM",
        "delivery_location": "Patiala Aggregation Center",
        "delivery_latitude": 30.3398,
        "delivery_longitude": 76.3869,
        "price_basis": "APMC_INDEXED",
        "quoted_price": 28.00,
        "currency": "INR",
        "price_unit": "INR_PER_KG",
        "payment_terms": "UPON_DELIVERY",
        "validity_start": date(2024, 9, 15),
        "validity_end": date(2024, 9, 30),
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REQ-PB-ONI-04",
        "source_reference": "FPO Collective Procurement (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # 5. Exporter Delhi - Onion (Export Grade A)
    {
        "id": "req_exporter_dl_onion",
        "buyer_id": "buyer_exporter_delhi",
        "commodity_id": "onion",
        "variety": "Pink / Red 45mm+",
        "minimum_quantity_kg": 10000.0,
        "maximum_quantity_kg": 50000.0,
        "preferred_quality_grade": "GRADE_A",
        "acceptable_quality_range": ["GRADE_A"],
        "required_from": date(2024, 9, 18),
        "required_until": date(2024, 10, 10),
        "delivery_mode": "BUYER_PREMISES",
        "delivery_location": "Azadpur Exporter Terminal",
        "delivery_latitude": 28.7159,
        "delivery_longitude": 77.1772,
        "price_basis": "FIXED_QUOTE",
        "quoted_price": 32.50,
        "currency": "INR",
        "price_unit": "INR_PER_KG",
        "payment_terms": "NET_15_DAYS",
        "validity_start": date(2024, 9, 18),
        "validity_end": date(2024, 10, 10),
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REQ-DL-ONI-05",
        "source_reference": "Export Container Consolidation (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # 6. Cooperative Haryana (Kalka) - Potato
    {
        "id": "req_coop_hr_potato",
        "buyer_id": "buyer_cooperative_haryana",
        "commodity_id": "potato",
        "variety": "Kufri Jyoti / Chandramukhi",
        "minimum_quantity_kg": 2000.0,
        "maximum_quantity_kg": 25000.0,
        "preferred_quality_grade": "GRADE_B",
        "acceptable_quality_range": ["GRADE_A", "GRADE_B", "GRADE_C"],
        "required_from": date(2024, 9, 15),
        "required_until": date(2024, 10, 15),
        "delivery_mode": "BUYER_PREMISES",
        "delivery_location": "Kalka HAFED Storage Yard",
        "delivery_latitude": 30.8354,
        "delivery_longitude": 76.9351,
        "price_basis": "FIXED_QUOTE",
        "quoted_price": 20.00,
        "currency": "INR",
        "price_unit": "INR_PER_KG",
        "payment_terms": "NET_7_DAYS",
        "validity_start": date(2024, 9, 15),
        "validity_end": date(2024, 10, 15),
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REQ-HR-POT-06",
        "source_reference": "Cooperative Procurement Notice (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # 7. Wholesaler Chandigarh - Onion
    {
        "id": "req_wholesaler_ch_onion",
        "buyer_id": "buyer_wholesaler_ch",
        "commodity_id": "onion",
        "variety": "General Desi",
        "minimum_quantity_kg": 1000.0,
        "maximum_quantity_kg": 10000.0,
        "preferred_quality_grade": "GRADE_B",
        "acceptable_quality_range": ["GRADE_A", "GRADE_B"],
        "required_from": date(2024, 9, 15),
        "required_until": date(2024, 9, 30),
        "delivery_mode": "MANDI_GATE",
        "delivery_location": "Chandigarh APMC Gate 2",
        "delivery_latitude": 30.7333,
        "delivery_longitude": 76.7794,
        "price_basis": "FIXED_QUOTE",
        "quoted_price": 28.50,
        "currency": "INR",
        "price_unit": "INR_PER_KG",
        "payment_terms": "IMMEDIATE_CASH",
        "validity_start": date(2024, 9, 15),
        "validity_end": date(2024, 9, 30),
        "source_name": "SYNTHETIC_DEMO_BENCHMARK",
        "source_record_id": "REQ-CH-ONI-07",
        "source_reference": "Mandi Board Quotation (Simulated)",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]

# Active Spot Demand Orders
DEMO_BUYER_DEMANDS: List[Dict[str, Any]] = [
    {
        "id": "dem_spot_tomato_01",
        "buyer_id": "buyer_wholesaler_ch",
        "commodity_id": "tomato",
        "variety": "Hybrid Red",
        "quantity_kg": 3000.0,
        "quality_requirement": "GRADE_A",
        "date_window_start": date(2024, 9, 15),
        "date_window_end": date(2024, 9, 22),
        "location": "Chandigarh APMC",
        "price_per_kg": 29.50,
        "price_unit": "INR_PER_KG",
        "demand_type": "DEMO_DEMAND",
        "demand_status": "ACTIVE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "dem_spot_tomato_02",
        "buyer_id": "buyer_retail_chain_pkl",
        "commodity_id": "tomato",
        "variety": "Grade A Hybrid",
        "quantity_kg": 4000.0,
        "quality_requirement": "GRADE_A",
        "date_window_start": date(2024, 9, 16),
        "date_window_end": date(2024, 9, 25),
        "location": "Panchkula Retail DC",
        "price_per_kg": 31.00,
        "price_unit": "INR_PER_KG",
        "demand_type": "DEMO_DEMAND",
        "demand_status": "ACTIVE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "dem_spot_tomato_03",
        "buyer_id": "buyer_processor_delhi",
        "commodity_id": "tomato",
        "variety": "Bulk Processing",
        "quantity_kg": 15000.0,
        "quality_requirement": "GRADE_B",
        "date_window_start": date(2024, 9, 17),
        "date_window_end": date(2024, 9, 30),
        "location": "Sonipat Food Park",
        "price_per_kg": 27.00,
        "price_unit": "INR_PER_KG",
        "demand_type": "DEMO_DEMAND",
        "demand_status": "ACTIVE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "dem_spot_onion_01",
        "buyer_id": "buyer_fpo_aggregator_pb",
        "commodity_id": "onion",
        "variety": "Medium Red",
        "quantity_kg": 8000.0,
        "quality_requirement": "GRADE_B",
        "date_window_start": date(2024, 9, 15),
        "date_window_end": date(2024, 9, 28),
        "location": "Patiala Center",
        "price_per_kg": 28.00,
        "price_unit": "INR_PER_KG",
        "demand_type": "DEMO_DEMAND",
        "demand_status": "ACTIVE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "dem_spot_onion_02",
        "buyer_id": "buyer_exporter_delhi",
        "commodity_id": "onion",
        "variety": "Export Red 50mm",
        "quantity_kg": 25000.0,
        "quality_requirement": "GRADE_A",
        "date_window_start": date(2024, 9, 20),
        "date_window_end": date(2024, 10, 5),
        "location": "Azadpur Exporter Hub",
        "price_per_kg": 32.50,
        "price_unit": "INR_PER_KG",
        "demand_type": "DEMO_DEMAND",
        "demand_status": "ACTIVE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "dem_spot_potato_01",
        "buyer_id": "buyer_cooperative_haryana",
        "commodity_id": "potato",
        "variety": "Jyoti Medium",
        "quantity_kg": 12000.0,
        "quality_requirement": "GRADE_B",
        "date_window_start": date(2024, 9, 15),
        "date_window_end": date(2024, 10, 10),
        "location": "Kalka Yard",
        "price_per_kg": 20.00,
        "price_unit": "INR_PER_KG",
        "demand_type": "DEMO_DEMAND",
        "demand_status": "ACTIVE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]

# Immutable Historical Transactions for Empirical Reliability Auditing
# (At least 3 transactions per buyer to satisfy N >= 3 statistical sufficiency)
DEMO_BUYER_TRANSACTIONS: List[Dict[str, Any]] = [
    # Buyer 1: Chandigarh Wholesaler (High volume, quick cash, reliable)
    {
        "id": "tx_ch_001",
        "buyer_id": "buyer_wholesaler_ch",
        "commodity_id": "tomato",
        "order_date": date(2024, 8, 1),
        "agreed_quantity_kg": 2000.0,
        "delivered_quantity_kg": 2000.0,
        "agreed_price_per_kg": 26.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 1),
        "actual_payment_date": date(2024, 8, 1),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_ch_002",
        "buyer_id": "buyer_wholesaler_ch",
        "commodity_id": "tomato",
        "order_date": date(2024, 8, 15),
        "agreed_quantity_kg": 3000.0,
        "delivered_quantity_kg": 2900.0,
        "agreed_price_per_kg": 28.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 15),
        "actual_payment_date": date(2024, 8, 15),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_ch_003",
        "buyer_id": "buyer_wholesaler_ch",
        "commodity_id": "tomato",
        "order_date": date(2024, 8, 28),
        "agreed_quantity_kg": 2500.0,
        "delivered_quantity_kg": 2500.0,
        "agreed_price_per_kg": 27.50,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 28),
        "actual_payment_date": date(2024, 8, 29),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_ch_004",
        "buyer_id": "buyer_wholesaler_ch",
        "commodity_id": "onion",
        "order_date": date(2024, 9, 2),
        "agreed_quantity_kg": 4000.0,
        "delivered_quantity_kg": 4000.0,
        "agreed_price_per_kg": 27.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 9, 2),
        "actual_payment_date": date(2024, 9, 2),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # Buyer 2: Northern Agro Processors (Institutional processor, Net 7, slight delays)
    {
        "id": "tx_proc_001",
        "buyer_id": "buyer_processor_delhi",
        "commodity_id": "tomato",
        "order_date": date(2024, 7, 10),
        "agreed_quantity_kg": 10000.0,
        "delivered_quantity_kg": 10000.0,
        "agreed_price_per_kg": 24.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 7, 17),
        "actual_payment_date": date(2024, 7, 17),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_proc_002",
        "buyer_id": "buyer_processor_delhi",
        "commodity_id": "tomato",
        "order_date": date(2024, 7, 25),
        "agreed_quantity_kg": 15000.0,
        "delivered_quantity_kg": 14200.0,
        "agreed_price_per_kg": 23.50,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "PARTIALLY_FULFILLED",
        "payment_status": "PAID_LATE",
        "agreed_payment_due_date": date(2024, 8, 1),
        "actual_payment_date": date(2024, 8, 5),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_proc_003",
        "buyer_id": "buyer_processor_delhi",
        "commodity_id": "tomato",
        "order_date": date(2024, 8, 12),
        "agreed_quantity_kg": 12000.0,
        "delivered_quantity_kg": 12000.0,
        "agreed_price_per_kg": 25.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 19),
        "actual_payment_date": date(2024, 8, 19),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # Buyer 3: KiranaFresh Retail Chain (Strict QA, Net 3 days, low dispute)
    {
        "id": "tx_ret_001",
        "buyer_id": "buyer_retail_chain_pkl",
        "commodity_id": "tomato",
        "order_date": date(2024, 8, 5),
        "agreed_quantity_kg": 2000.0,
        "delivered_quantity_kg": 2000.0,
        "agreed_price_per_kg": 30.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 8),
        "actual_payment_date": date(2024, 8, 8),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_ret_002",
        "buyer_id": "buyer_retail_chain_pkl",
        "commodity_id": "tomato",
        "order_date": date(2024, 8, 18),
        "agreed_quantity_kg": 3000.0,
        "delivered_quantity_kg": 2800.0,
        "agreed_price_per_kg": 31.50,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "PARTIALLY_FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 21),
        "actual_payment_date": date(2024, 8, 21),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_ret_003",
        "buyer_id": "buyer_retail_chain_pkl",
        "commodity_id": "tomato",
        "order_date": date(2024, 9, 1),
        "agreed_quantity_kg": 2500.0,
        "delivered_quantity_kg": 2500.0,
        "agreed_price_per_kg": 30.50,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 9, 4),
        "actual_payment_date": date(2024, 9, 4),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # Buyer 4: Malwa Kisan FPO Aggregator (Fair trade, prompt delivery)
    {
        "id": "tx_fpo_001",
        "buyer_id": "buyer_fpo_aggregator_pb",
        "commodity_id": "onion",
        "order_date": date(2024, 7, 20),
        "agreed_quantity_kg": 5000.0,
        "delivered_quantity_kg": 5000.0,
        "agreed_price_per_kg": 26.50,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 7, 20),
        "actual_payment_date": date(2024, 7, 20),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_fpo_002",
        "buyer_id": "buyer_fpo_aggregator_pb",
        "commodity_id": "onion",
        "order_date": date(2024, 8, 10),
        "agreed_quantity_kg": 6000.0,
        "delivered_quantity_kg": 6000.0,
        "agreed_price_per_kg": 27.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 10),
        "actual_payment_date": date(2024, 8, 10),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_fpo_003",
        "buyer_id": "buyer_fpo_aggregator_pb",
        "commodity_id": "onion",
        "order_date": date(2024, 8, 26),
        "agreed_quantity_kg": 7500.0,
        "delivered_quantity_kg": 7500.0,
        "agreed_price_per_kg": 27.80,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 26),
        "actual_payment_date": date(2024, 8, 26),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # Buyer 5: Indo-Gulf Fresh Exports Cargo (Export documentation, Net 15)
    {
        "id": "tx_exp_001",
        "buyer_id": "buyer_exporter_delhi",
        "commodity_id": "onion",
        "order_date": date(2024, 7, 5),
        "agreed_quantity_kg": 20000.0,
        "delivered_quantity_kg": 20000.0,
        "agreed_price_per_kg": 30.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 7, 20),
        "actual_payment_date": date(2024, 7, 20),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_exp_002",
        "buyer_id": "buyer_exporter_delhi",
        "commodity_id": "onion",
        "order_date": date(2024, 7, 28),
        "agreed_quantity_kg": 25000.0,
        "delivered_quantity_kg": 24000.0,
        "agreed_price_per_kg": 31.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "PARTIALLY_FULFILLED",
        "payment_status": "PAID_LATE",
        "agreed_payment_due_date": date(2024, 8, 12),
        "actual_payment_date": date(2024, 8, 17),
        "dispute_status": True,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_exp_003",
        "buyer_id": "buyer_exporter_delhi",
        "commodity_id": "onion",
        "order_date": date(2024, 8, 20),
        "agreed_quantity_kg": 22000.0,
        "delivered_quantity_kg": 22000.0,
        "agreed_price_per_kg": 31.50,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 9, 4),
        "actual_payment_date": date(2024, 9, 4),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    # Buyer 6: Haryana Krishi Sahakari Sangh (HAFED Center - Potato)
    {
        "id": "tx_coop_001",
        "buyer_id": "buyer_cooperative_haryana",
        "commodity_id": "potato",
        "order_date": date(2024, 7, 15),
        "agreed_quantity_kg": 10000.0,
        "delivered_quantity_kg": 10000.0,
        "agreed_price_per_kg": 18.50,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 7, 22),
        "actual_payment_date": date(2024, 7, 22),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_coop_002",
        "buyer_id": "buyer_cooperative_haryana",
        "commodity_id": "potato",
        "order_date": date(2024, 8, 2),
        "agreed_quantity_kg": 15000.0,
        "delivered_quantity_kg": 15000.0,
        "agreed_price_per_kg": 19.00,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 8, 9),
        "actual_payment_date": date(2024, 8, 9),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "tx_coop_003",
        "buyer_id": "buyer_cooperative_haryana",
        "commodity_id": "potato",
        "order_date": date(2024, 8, 25),
        "agreed_quantity_kg": 12000.0,
        "delivered_quantity_kg": 12000.0,
        "agreed_price_per_kg": 19.50,
        "price_unit": "INR_PER_KG",
        "fulfillment_status": "FULFILLED",
        "payment_status": "PAID_ON_TIME",
        "agreed_payment_due_date": date(2024, 9, 1),
        "actual_payment_date": date(2024, 9, 3),
        "dispute_status": False,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]

# Benchmark Sample Farmer Supplies for Matching Demonstration
DEMO_FARMER_SUPPLIES: List[Dict[str, Any]] = [
    {
        "id": "supply_demo_tomato_01",
        "supply_reference_id": "LOT-TOM-CH-2024-001",
        "commodity_id": "tomato",
        "variety": "Hybrid Red",
        "quantity_kg": 2500.0,
        "quality_grade": "GRADE_A",
        "available_from": date(2024, 9, 15),
        "available_until": date(2024, 9, 22),
        "origin_location": "Mohali Rural Farmgate",
        "origin_latitude": 30.6970,
        "origin_longitude": 76.6948,
        "storage_available": False,
        "storage_type": None,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "supply_demo_onion_01",
        "supply_reference_id": "LOT-ONI-PB-2024-002",
        "commodity_id": "onion",
        "variety": "Nasik Red",
        "quantity_kg": 8000.0,
        "quality_grade": "GRADE_B",
        "available_from": date(2024, 9, 15),
        "available_until": date(2024, 9, 30),
        "origin_location": "Patiala Rural Farmgate",
        "origin_latitude": 30.3398,
        "origin_longitude": 76.3869,
        "storage_available": True,
        "storage_type": "VENTILATED_SHED",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]
