"""
AgriClutch Step 13 Logistics & Storage Demo Seed Fixtures.
Explicitly tagged synthetic archetypes with is_demo=True and provenance_status='DEMO'.
Uses clearly synthetic identifiers to avoid implying verified physical infrastructure.
SIH26132 — Strengthening Market Linkages and Price Discovery for Farmers.
"""

from typing import Any, Dict, List

DEMO_TRANSPORT_MODES: List[Dict[str, Any]] = [
    {
        "id": "DEMO_TRACTOR_TROLLEY",
        "display_name": "Tractor Trolley (Short-Haul Farm Transport)",
        "vehicle_type": "TRACTOR_TROLLEY",
        "capacity_kg": 1500.0,
        "base_dispatch_fee": 500.0,
        "cost_per_km": 18.0,
        "cost_per_km_tonne": 12.0,
        "speed_kmh": 25.0,
        "temperature_controlled": False,
        "active_status": True,
        "source_name": "DEMO_VEHICLE_ARCHETYPE_SCHEDULE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "DEMO_LCV_TATA_407",
        "display_name": "Light Commercial Vehicle (LCV - Tata 407 Archetype)",
        "vehicle_type": "LCV",
        "capacity_kg": 2500.0,
        "base_dispatch_fee": 800.0,
        "cost_per_km": 25.0,
        "cost_per_km_tonne": 10.0,
        "speed_kmh": 45.0,
        "temperature_controlled": False,
        "active_status": True,
        "source_name": "DEMO_VEHICLE_ARCHETYPE_SCHEDULE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "DEMO_HEAVY_TRUCK_10T",
        "display_name": "Medium/Heavy Commercial Vehicle (10-Tonne Multi-Axle)",
        "vehicle_type": "HEAVY_TRUCK",
        "capacity_kg": 10000.0,
        "base_dispatch_fee": 2500.0,
        "cost_per_km": 55.0,
        "cost_per_km_tonne": 5.5,
        "speed_kmh": 40.0,
        "temperature_controlled": False,
        "active_status": True,
        "source_name": "DEMO_VEHICLE_ARCHETYPE_SCHEDULE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "DEMO_REEFER_CONTAINER",
        "display_name": "Refrigerated Container Truck (Cold Chain Reefer)",
        "vehicle_type": "REEFER",
        "capacity_kg": 8000.0,
        "base_dispatch_fee": 3500.0,
        "cost_per_km": 75.0,
        "cost_per_km_tonne": 9.38,
        "speed_kmh": 50.0,
        "temperature_controlled": True,
        "active_status": True,
        "source_name": "DEMO_VEHICLE_ARCHETYPE_SCHEDULE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]

DEMO_STORAGE_FACILITIES: List[Dict[str, Any]] = [
    {
        "id": "DEMO_WAREHOUSE_MOHALI",
        "facility_name": "Mohali Demo Ventilated Warehouse",
        "storage_type": "VENTILATED",
        "location": "Mohali Industrial Area Phase 8, Punjab",
        "latitude": 30.7050,
        "longitude": 76.7150,
        "total_capacity_kg": 100000.0,
        "available_capacity_kg": 35000.0,
        "cost_per_kg_day": 0.15,
        "min_duration_days": 2,
        "max_duration_days": 60,
        "temperature_celsius": 24.0,
        "humidity_pct": 65.0,
        "active_status": True,
        "source_name": "DEMO_FACILITY_BENCHMARK_SCHEDULE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "DEMO_COLD_STORAGE_NORTH",
        "facility_name": "Demo Northern Cold Chain Terminal",
        "storage_type": "COLD",
        "location": "Zirakpur Logistics Park, Punjab",
        "latitude": 30.6400,
        "longitude": 76.8200,
        "total_capacity_kg": 250000.0,
        "available_capacity_kg": 75000.0,
        "cost_per_kg_day": 0.25,
        "min_duration_days": 3,
        "max_duration_days": 90,
        "temperature_celsius": 10.0,
        "humidity_pct": 92.0,
        "active_status": True,
        "source_name": "DEMO_FACILITY_BENCHMARK_SCHEDULE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "DEMO_SILO_PUNJAB",
        "facility_name": "Punjab Demo Grain & Bulk Silo Hub",
        "storage_type": "VENTILATED",
        "location": "Patiala Road Logistics Node, Punjab",
        "latitude": 30.3400,
        "longitude": 76.4000,
        "total_capacity_kg": 500000.0,
        "available_capacity_kg": 150000.0,
        "cost_per_kg_day": 0.10,
        "min_duration_days": 7,
        "max_duration_days": 180,
        "temperature_celsius": 22.0,
        "humidity_pct": 55.0,
        "active_status": True,
        "source_name": "DEMO_FACILITY_BENCHMARK_SCHEDULE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "DEMO_COLD_CHAIN_DELHI",
        "facility_name": "Delhi Terminal Demo Cold Chain Hub",
        "storage_type": "COLD",
        "location": "Kundli Logistics Corridor, NCR",
        "latitude": 28.8700,
        "longitude": 77.1200,
        "total_capacity_kg": 500000.0,
        "available_capacity_kg": 120000.0,
        "cost_per_kg_day": 0.35,
        "min_duration_days": 1,
        "max_duration_days": 60,
        "temperature_celsius": 4.0,
        "humidity_pct": 95.0,
        "active_status": True,
        "source_name": "DEMO_FACILITY_BENCHMARK_SCHEDULE",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]

DEMO_LOGISTICS_ROUTES: List[Dict[str, Any]] = [
    {
        "id": "ROUTE_KALKA_CHD_APMC",
        "origin_name": "Kalka Farm Gate",
        "destination_name": "Chandigarh APMC Mandi",
        "origin_lat": 30.8350,
        "origin_lon": 76.9350,
        "destination_lat": 30.7250,
        "destination_lon": 76.8000,
        "straight_line_distance_km": 17.5,
        "road_distance_km": 24.0,
        "typical_duration_hours": 0.8,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "ROUTE_KALKA_MOHALI_BUYER",
        "origin_name": "Kalka Farm Gate",
        "destination_name": "Mohali Sector 82 Buyer Hub",
        "origin_lat": 30.8350,
        "origin_lon": 76.9350,
        "destination_lat": 30.6800,
        "destination_lon": 76.7200,
        "straight_line_distance_km": 26.8,
        "road_distance_km": 34.5,
        "typical_duration_hours": 1.1,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "ROUTE_KALKA_AZADPUR_MANDI",
        "origin_name": "Kalka Farm Gate",
        "destination_name": "Azadpur APMC Mandi Delhi",
        "origin_lat": 30.8350,
        "origin_lon": 76.9350,
        "destination_lat": 28.7150,
        "destination_lon": 77.1750,
        "straight_line_distance_km": 236.0,
        "road_distance_km": 258.0,
        "typical_duration_hours": 5.5,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "ROUTE_PATIALA_CHD_APMC",
        "origin_name": "Patiala Farm Node",
        "destination_name": "Chandigarh APMC Mandi",
        "origin_lat": 30.3400,
        "origin_lon": 76.4000,
        "destination_lat": 30.7250,
        "destination_lon": 76.8000,
        "straight_line_distance_km": 57.2,
        "road_distance_km": 68.0,
        "typical_duration_hours": 1.6,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "ROUTE_PANCHKULA_CHD_APMC",
        "origin_name": "Panchkula Farm Node",
        "destination_name": "Chandigarh APMC Mandi",
        "origin_lat": 30.6950,
        "origin_lon": 76.8600,
        "destination_lat": 30.7250,
        "destination_lon": 76.8000,
        "straight_line_distance_km": 6.8,
        "road_distance_km": 9.5,
        "typical_duration_hours": 0.4,
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]

DEMO_PERISHABILITY_PARAMETERS: List[Dict[str, Any]] = [
    {
        "id": "PERISH_TOMATO_AMBIENT",
        "commodity_id": "tomato",
        "storage_type": "AMBIENT",
        "decay_parameter_delta": 0.035,
        "quality_decay_beta": 0.050,
        "equation": "S(t) = exp(-0.035 * t); Q_eff(t) = Q0 * S(t); F_qual(t) = F0 * exp(-0.050 * t)",
        "assumptions": "Uncontrolled ambient conditions (28-35°C). Non-refrigerated holding.",
        "source_name": "DEMO_PERISHABILITY_ASSUMPTION_SCHEDULE",
        "calibration_status": "NOT_CALIBRATED",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "PERISH_TOMATO_COLD",
        "commodity_id": "tomato",
        "storage_type": "COLD",
        "decay_parameter_delta": 0.008,
        "quality_decay_beta": 0.015,
        "equation": "S(t) = exp(-0.008 * t); Q_eff(t) = Q0 * S(t); F_qual(t) = F0 * exp(-0.015 * t)",
        "assumptions": "Cold chain holding (10-12°C, 90-95% RH). Controlled atmosphere.",
        "source_name": "DEMO_PERISHABILITY_ASSUMPTION_SCHEDULE",
        "calibration_status": "NOT_CALIBRATED",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "PERISH_ONION_AMBIENT",
        "commodity_id": "onion",
        "storage_type": "AMBIENT",
        "decay_parameter_delta": 0.005,
        "quality_decay_beta": 0.008,
        "equation": "S(t) = exp(-0.005 * t); Q_eff(t) = Q0 * S(t); F_qual(t) = F0 * exp(-0.008 * t)",
        "assumptions": "Traditional well-ventilated chawl/shed storage (dry, shade).",
        "source_name": "DEMO_PERISHABILITY_ASSUMPTION_SCHEDULE",
        "calibration_status": "NOT_CALIBRATED",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "PERISH_ONION_COLD",
        "commodity_id": "onion",
        "storage_type": "COLD",
        "decay_parameter_delta": 0.0015,
        "quality_decay_beta": 0.003,
        "equation": "S(t) = exp(-0.0015 * t); Q_eff(t) = Q0 * S(t); F_qual(t) = F0 * exp(-0.003 * t)",
        "assumptions": "Commercial cold store (0-2°C, 65-70% RH). Dehumidified.",
        "source_name": "DEMO_PERISHABILITY_ASSUMPTION_SCHEDULE",
        "calibration_status": "NOT_CALIBRATED",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "PERISH_POTATO_AMBIENT",
        "commodity_id": "potato",
        "storage_type": "AMBIENT",
        "decay_parameter_delta": 0.004,
        "quality_decay_beta": 0.006,
        "equation": "S(t) = exp(-0.004 * t); Q_eff(t) = Q0 * S(t); F_qual(t) = F0 * exp(-0.006 * t)",
        "assumptions": "Traditional farm ambient heap / pit storage (dark, ventilated).",
        "source_name": "DEMO_PERISHABILITY_ASSUMPTION_SCHEDULE",
        "calibration_status": "NOT_CALIBRATED",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
    {
        "id": "PERISH_POTATO_COLD",
        "commodity_id": "potato",
        "storage_type": "COLD",
        "decay_parameter_delta": 0.0008,
        "quality_decay_beta": 0.0015,
        "equation": "S(t) = exp(-0.0008 * t); Q_eff(t) = Q0 * S(t); F_qual(t) = F0 * exp(-0.0015 * t)",
        "assumptions": "Commercial potato cold store (2-4°C, 95% RH with sprout inhibitor).",
        "source_name": "DEMO_PERISHABILITY_ASSUMPTION_SCHEDULE",
        "calibration_status": "NOT_CALIBRATED",
        "provenance_status": "DEMO",
        "is_demo": True,
    },
]
