"""
Verified Benchmark Seed Data Fixtures for AgriClutch Demo Mode.
Provides 100% offline fallback when PostgreSQL/TimescaleDB is disconnected.
All records are explicitly labeled: is_demo: True, source_name: "SYNTHETIC_DEMO".
SIH26132 — Market Linkages and Price Discovery for Farmers.
"""

from datetime import date, datetime, timezone
from typing import List, Optional
from uuid import UUID

from app.schemas.commodity import CommodityResponse, CropCategory
from app.schemas.market import MarketResponse
from app.schemas.price_observation import PriceObservationResponse

SEED_TIMESTAMP = datetime(2024, 9, 15, 0, 0, 0, tzinfo=timezone.utc)

# 1. Authoritative Seed Commodities
SEED_COMMODITIES: List[CommodityResponse] = [
    CommodityResponse(
        id="tomato",
        name="Tomato",
        hindi_name="टमाटर",
        category=CropCategory.PERISHABLE,
        default_spoilage_rate=0.08,
        max_ambient_holding_days=4,
        standard_moisture_pct=94.0,
        price_unit="INR_PER_KG",
        weight_unit="KG",
        created_at=SEED_TIMESTAMP,
    ),
    CommodityResponse(
        id="onion",
        name="Onion",
        hindi_name="प्याज",
        category=CropCategory.SEMI_PERISHABLE,
        default_spoilage_rate=0.015,
        max_ambient_holding_days=30,
        standard_moisture_pct=86.0,
        price_unit="INR_PER_KG",
        weight_unit="KG",
        created_at=SEED_TIMESTAMP,
    ),
    CommodityResponse(
        id="potato",
        name="Potato",
        hindi_name="आलू",
        category=CropCategory.STORABLE,
        default_spoilage_rate=0.005,
        max_ambient_holding_days=180,
        standard_moisture_pct=79.0,
        price_unit="INR_PER_KG",
        weight_unit="KG",
        created_at=SEED_TIMESTAMP,
    ),
]

# 2. Authoritative Seed APMC Markets
SEED_MARKETS: List[MarketResponse] = [
    MarketResponse(
        id="mandi_ch_49",
        apmc_code=49,
        name="Chandigarh (APMC)",
        state="Chandigarh",
        district="Chandigarh",
        latitude=30.7333,
        longitude=76.7794,
        is_terminal_market=False,
        dca_centre_id=None,
        source_market_id="Chandigarh(Grain)",
        created_at=SEED_TIMESTAMP,
    ),
    MarketResponse(
        id="mandi_hr_01",
        apmc_code=1,
        name="Panchkula (Haryana)",
        state="Haryana",
        district="Panchkula",
        latitude=30.6942,
        longitude=76.8606,
        is_terminal_market=False,
        dca_centre_id=None,
        source_market_id="Panchkula",
        created_at=SEED_TIMESTAMP,
    ),
    MarketResponse(
        id="mandi_hr_02",
        apmc_code=2,
        name="Kalka (Haryana)",
        state="Haryana",
        district="Panchkula",
        latitude=30.8333,
        longitude=76.9333,
        is_terminal_market=False,
        dca_centre_id=None,
        source_market_id="Kalka",
        created_at=SEED_TIMESTAMP,
    ),
    MarketResponse(
        id="mandi_pb_12",
        apmc_code=12,
        name="Patiala (Punjab)",
        state="Punjab",
        district="Patiala",
        latitude=30.3398,
        longitude=76.3869,
        is_terminal_market=False,
        dca_centre_id=None,
        source_market_id="Patiala",
        created_at=SEED_TIMESTAMP,
    ),
    MarketResponse(
        id="mandi_dl_164",
        apmc_code=164,
        name="Azadpur (Delhi Terminal)",
        state="Delhi",
        district="North Delhi",
        latitude=28.7161,
        longitude=77.1706,
        is_terminal_market=True,
        dca_centre_id=1,
        source_market_id="Azadpur",
        created_at=SEED_TIMESTAMP,
    ),
]

# 3. Authoritative Seed Observations
SEED_PRICES: List[PriceObservationResponse] = [
    # Tomato - Chandigarh (APMC)
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000001"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_001",
        source_market_id="Chandigarh",
        source_commodity_id="Tomato",
        market_id="mandi_ch_49",
        commodity_id="tomato",
        record_date=date(2024, 9, 10),
        variety="Common",
        grade="FAQ",
        original_modal_price=2800.0,
        original_min_price=2500.0,
        original_max_price=3000.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=28.00,
        normalized_min_price=25.00,
        normalized_max_price=30.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=42.5,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000002"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_002",
        source_market_id="Chandigarh",
        source_commodity_id="Tomato",
        market_id="mandi_ch_49",
        commodity_id="tomato",
        record_date=date(2024, 9, 11),
        variety="Common",
        grade="FAQ",
        original_modal_price=2850.0,
        original_min_price=2600.0,
        original_max_price=3100.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=28.50,
        normalized_min_price=26.00,
        normalized_max_price=31.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=40.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000003"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_003",
        source_market_id="Chandigarh",
        source_commodity_id="Tomato",
        market_id="mandi_ch_49",
        commodity_id="tomato",
        record_date=date(2024, 9, 12),
        variety="Common",
        grade="FAQ",
        original_modal_price=2900.0,
        original_min_price=2650.0,
        original_max_price=3150.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=29.00,
        normalized_min_price=26.50,
        normalized_max_price=31.50,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=38.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000004"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_004",
        source_market_id="Chandigarh",
        source_commodity_id="Tomato",
        market_id="mandi_ch_49",
        commodity_id="tomato",
        record_date=date(2024, 9, 13),
        variety="Common",
        grade="FAQ",
        original_modal_price=3000.0,
        original_min_price=2700.0,
        original_max_price=3200.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=30.00,
        normalized_min_price=27.00,
        normalized_max_price=32.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=35.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000005"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_005",
        source_market_id="Chandigarh",
        source_commodity_id="Tomato",
        market_id="mandi_ch_49",
        commodity_id="tomato",
        record_date=date(2024, 9, 14),
        variety="Common",
        grade="FAQ",
        original_modal_price=2950.0,
        original_min_price=2700.0,
        original_max_price=3100.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=29.50,
        normalized_min_price=27.00,
        normalized_max_price=31.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=45.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),

    # Tomato - Panchkula (Haryana)
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000006"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_006",
        source_market_id="Panchkula",
        source_commodity_id="Tomato",
        market_id="mandi_hr_01",
        commodity_id="tomato",
        record_date=date(2024, 9, 10),
        variety="Common",
        grade="FAQ",
        original_modal_price=2750.0,
        original_min_price=2450.0,
        original_max_price=2950.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=27.50,
        normalized_min_price=24.50,
        normalized_max_price=29.50,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=18.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000007"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_007",
        source_market_id="Panchkula",
        source_commodity_id="Tomato",
        market_id="mandi_hr_01",
        commodity_id="tomato",
        record_date=date(2024, 9, 11),
        variety="Common",
        grade="FAQ",
        original_modal_price=2800.0,
        original_min_price=2500.0,
        original_max_price=3000.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=28.00,
        normalized_min_price=25.00,
        normalized_max_price=30.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=16.5,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000008"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_008",
        source_market_id="Panchkula",
        source_commodity_id="Tomato",
        market_id="mandi_hr_01",
        commodity_id="tomato",
        record_date=date(2024, 9, 12),
        variety="Common",
        grade="FAQ",
        original_modal_price=2850.0,
        original_min_price=2550.0,
        original_max_price=3050.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=28.50,
        normalized_min_price=25.50,
        normalized_max_price=30.50,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=15.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),

    # Tomato - Azadpur (Delhi Terminal)
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000014"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_014",
        source_market_id="Azadpur",
        source_commodity_id="Tomato",
        market_id="mandi_dl_164",
        commodity_id="tomato",
        record_date=date(2024, 9, 10),
        variety="Common",
        grade="FAQ",
        original_modal_price=3100.0,
        original_min_price=2800.0,
        original_max_price=3400.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=31.00,
        normalized_min_price=28.00,
        normalized_max_price=34.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=210.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000015"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_015",
        source_market_id="Azadpur",
        source_commodity_id="Tomato",
        market_id="mandi_dl_164",
        commodity_id="tomato",
        record_date=date(2024, 9, 11),
        variety="Common",
        grade="FAQ",
        original_modal_price=3150.0,
        original_min_price=2850.0,
        original_max_price=3450.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=31.50,
        normalized_min_price=28.50,
        normalized_max_price=34.50,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=195.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),

    # Onion - Chandigarh (APMC)
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000009"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_009",
        source_market_id="Chandigarh",
        source_commodity_id="Onion",
        market_id="mandi_ch_49",
        commodity_id="onion",
        record_date=date(2024, 9, 10),
        variety="Common",
        grade="FAQ",
        original_modal_price=3200.0,
        original_min_price=2900.0,
        original_max_price=3500.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=32.00,
        normalized_min_price=29.00,
        normalized_max_price=35.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=65.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000010"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_010",
        source_market_id="Chandigarh",
        source_commodity_id="Onion",
        market_id="mandi_ch_49",
        commodity_id="onion",
        record_date=date(2024, 9, 11),
        variety="Common",
        grade="FAQ",
        original_modal_price=3250.0,
        original_min_price=3000.0,
        original_max_price=3550.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=32.50,
        normalized_min_price=30.00,
        normalized_max_price=35.50,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=60.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000011"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_011",
        source_market_id="Chandigarh",
        source_commodity_id="Onion",
        market_id="mandi_ch_49",
        commodity_id="onion",
        record_date=date(2024, 9, 12),
        variety="Common",
        grade="FAQ",
        original_modal_price=3300.0,
        original_min_price=3000.0,
        original_max_price=3600.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=33.00,
        normalized_min_price=30.00,
        normalized_max_price=36.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=58.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),

    # Potato - Patiala (Punjab)
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000012"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_012",
        source_market_id="Patiala",
        source_commodity_id="Potato",
        market_id="mandi_pb_12",
        commodity_id="potato",
        record_date=date(2024, 9, 10),
        variety="Common",
        grade="FAQ",
        original_modal_price=1800.0,
        original_min_price=1600.0,
        original_max_price=2000.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=18.00,
        normalized_min_price=16.00,
        normalized_max_price=20.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=85.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
    PriceObservationResponse(
        observation_id=UUID("00000000-0000-0000-0000-000000000013"),
        source_name="SYNTHETIC_DEMO",
        source_record_id="SYN_013",
        source_market_id="Patiala",
        source_commodity_id="Potato",
        market_id="mandi_pb_12",
        commodity_id="potato",
        record_date=date(2024, 9, 11),
        variety="Common",
        grade="FAQ",
        original_modal_price=1820.0,
        original_min_price=1650.0,
        original_max_price=2000.0,
        original_price_unit="Rs/Quintal",
        normalized_modal_price=18.20,
        normalized_min_price=16.50,
        normalized_max_price=20.00,
        normalized_price_unit="INR_PER_KG",
        arrival_tonnes=82.0,
        is_interpolated=False,
        is_outlier=False,
        created_at=SEED_TIMESTAMP,
    ),
]


def filter_seed_commodities(category: Optional[CropCategory] = None) -> List[CommodityResponse]:
    """Filters seed commodities by category."""
    if not category:
        return SEED_COMMODITIES
    return [c for c in SEED_COMMODITIES if c.category == category]


def filter_seed_markets(
    state: Optional[str] = None, is_terminal: Optional[bool] = None
) -> List[MarketResponse]:
    """Filters seed mandis by state and terminal status."""
    res = SEED_MARKETS
    if state:
        res = [m for m in res if m.state.lower() == state.lower()]
    if is_terminal is not None:
        res = [m for m in res if m.is_terminal_market == is_terminal]
    return res


def filter_seed_prices(
    commodity_id: Optional[str] = None,
    market_id: Optional[str] = None,
    start_date: Optional[date] = None,
    end_date: Optional[date] = None,
    limit: int = 100,
    offset: int = 0,
) -> tuple[List[PriceObservationResponse], int]:
    """Filters seed prices by multi-dimensional query params."""
    res = SEED_PRICES
    if commodity_id:
        res = [p for p in res if p.commodity_id.lower() == commodity_id.lower()]
    if market_id:
        res = [p for p in res if p.market_id.lower() == market_id.lower()]
    if start_date:
        res = [p for p in res if p.record_date >= start_date]
    if end_date:
        res = [p for p in res if p.record_date <= end_date]

    # Sort descending by record_date
    res = sorted(res, key=lambda p: p.record_date, reverse=True)
    total = len(res)
    paginated = res[offset : offset + limit]
    return paginated, total
